### ISSUE TITLE
reset Pano 

### ISSUE THREAD

**Issue by ashrafreda** [mudin/vue-vr#11]
Hi,
thanks for your work.
How to reset the pano sizes after opening it in the bootstrap modal?

**Comment by mudin** [comment]
please call `onResize` function

**Comment by ashrafreda** [comment]
sorry, but can you tell me how?

**Comment by mudin** [comment]
in template: 
`<Pano ref="pano" ...`
in js:
`this.$refs.pano.onResize()`

**Comment by ashrafreda** [comment]
this raises this error:
`handler: "TypeError: Cannot read property 'onResize' of undefined"`

**Comment by mudin** [comment]
please share your code

**Comment by ashrafreda** [comment]
I use Vue bootstrap, and use the <pano> in bootstrap modal

in template:
`<b-link @click="showPropeModal()">Open</b-link>`

`<b-tab title="tab content">
    <pano ref="pano" :source="require('../../assets/images/360-img-preview-1.jpg')"  @on-load="panoOnload">
    </pano>
</b-tab>`

in Js:
`methods: {
        showPropeModal() {
            this.$refs['listing-details'].show();
            this.$refs.pano.onResize();
        },
}`

**Comment by mudin** [comment]
How about calling `window.dispatchEvent(new Event('resize'));`?

**Comment by ashrafreda** [comment]
Sorry, but it still not working.

**Comment by mudin** [comment]
Then it is not the library issue, please make sure you gave enough width and height for pano component

**Comment by ashrafreda** [comment]
Yes, I know that isn't a library issue, It works correctly when changing the size of window after opening the modal, so I ask for how to call the correct resize event.

Thanks, Mudin.
