### ISSUE TITLE
image not load until resize window

### ISSUE THREAD

**Issue by lochawala** [mudin/vue-vr#14]
Hello 

i faced issue in one of my component that have dynamic height so in that if i resize my window size then only 360 image is load until it's shows me black window and if i use this component in model popup then also image is not load.

i am using old vue material design 

https://vue-material-old.netlify.com/#/

using below two component
https://vue-material-old.netlify.com/#/components/tabs
https://vue-material-old.netlify.com/#/components/dialog

**Comment by mudin** [comment]
Hi
can you share jsfiddle or codesandbox?
It will help to find out the problem

**Comment by lochawala** [comment]
Hi 

It's issue in my tab component that we used so changed it and now it's working fine 

Thanks
