### ISSUE TITLE
vr img cannot be shown correctly

### ISSUE THREAD

**Issue by KobeBeyond** [mudin/vue-vr#16]
![image](https://user-images.githubusercontent.com/41274333/80306983-f1683900-87f8-11ea-9ed2-40fecbaf4629.png)
![image](https://user-images.githubusercontent.com/41274333/80306988-fc22ce00-87f8-11ea-840b-6d7bf82feb14.png)

![image](https://user-images.githubusercontent.com/41274333/80307046-56bc2a00-87f9-11ea-9098-e33729855de0.png)

**Comment by mudin** [comment]
@KobeBeyond you should do some css there
