### ISSUE TITLE
Using sequence images

### ISSUE THREAD

**Issue by over12** [mudin/vue-vr#17]
is it possible to create a 360 with sequences of images, for example, image_1 through image_40?

**Comment by mudin** [comment]
I didn't understand your question well. Is there any sample image?

**Comment by over12** [comment]
Hi @mudin ,
Yes, I have an example, here's a print: https://prnt.sc/sk5s44

**Comment by over12** [comment]
Hi @mudin, its possible?

**Comment by mudin** [comment]
@over12 sorry it is not possible. I think what you are looking for is something like this https://ggnome.com/object2vr/
