### ISSUE TITLE
WebGL: INVALID_VALUE: texImage2D: no video

### ISSUE THREAD

**Issue by mrclaytorres** [mudin/vue-vr#19]
Hi mudin,

Thank you for this library, I'm loving it. Just one issue I'm getting and I can figure out what it is. When I use a 360 video with a .mp4 filename, I get this error:

`WebGL: INVALID_VALUE: texImage2D: no video`

`[.WebGL-00000272E2E6A130]RENDER WARNING: texture bound to texture unit 0 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?`

Thank you.

**Environment**
Vue version 2.6.12
Browser & Version: Google Chrome Version 87.0.4280.66
OS & Version: Windows 10 1909

**Comment by mrclaytorres** [comment]
Hi @mudin,

Thank you for responding. You can check my test here: http://nhstest-co-uk.stackstaging.com/nhs-vr/index.html

Alternatively, you can check the .mp4 360 video I used here: http://nhstest-co-uk.stackstaging.com/nhs-vr/media/SC2-Option-1A.mp4

Let me know if you need more information.

Thank you.

**Comment by mudin** [comment]
@mrclaytorres 
There are some issue in your video I guess,
I tried to open in browser itself, it is black.
But I fixed the other issue related to play without user interaction.
Please try to use version 1.2.2

**Comment by mrclaytorres** [comment]
Hi @mudin,

I see, thank you for the valuable insight on video, I'll try to check if I improve the video encoding.

Thank you for version 1.2.2. I'll update my copy.

I really hope your project continues, as I haven't seen any other VR technology that utilizes Vue yet.

All the best.

Side question if you don't mind, does Pano's source attribute can be use with a v-bind directive?

**Comment by mudin** [comment]
@mrclaytorres 
You're welcome

> :Side question if you don't mind, does Pano's source attribute can be use with a v-bind directive?

Yes it does!
