### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by damisparks** [mudin/vue-vr#28]
I am trying to implement this **nuxtjs**, but it is not working. 

Here are the steps I have taken so far. 
* install the package.
```html
 <client-only>
        <Pano type="video" :source="src"></Pano>
 </client-only>
```
* import the library as described on the docs.

Any ideas or suggestions on how to solve this will be appreciated.

**Comment by damisparks** [comment]
> I am trying to implement this **nuxtjs**, but it is not working.
> 
> Here are the steps I have taken so far.
> 
> * install the package.
> 
> ```
>  <client-only>
>         <Pano type="video" :source="src"></Pano>
>  </client-only>
> ```
> 
>  * import the library as described on the docs.
> 
> Any ideas or suggestions on how to solve this will be appreciated.

Never mind. I went with another package.

**Comment by saidbanawir** [comment]
> 

what your package use ???

**Comment by damisparks** [comment]
> what your package use ???

@saidbanawir I decided to build something from scratch.
