### ISSUE TITLE
Lazy load on images

### ISSUE THREAD

**Issue by samirortiz** [mudin/vue-vr#6]
Can i use lazy load on images into Pano?

**Comment by mudin** [comment]
@samirortiz Currently multiresolution is not supported, You can use cubefaces

**Comment by samirortiz** [comment]
Hmm i see, but actually my problem is to inject to many Panos (about 20) inside the component. 
I have a the Panos inside a carousel. 
Can i change only the source image from Pano, on demand? So i can use only one Pano and change his source image.

**Comment by mudin** [comment]
@samirortiz I have released the 1.1.0 version, I fixed the issue with dynamic `source` attribute in `Pano`.

**Comment by mudin** [comment]
@samirortiz https://mudin.github.io/vue-vr/#/demo-pano check the demo

**Comment by samirortiz** [comment]
Thanks man, awesome, it's working for me now, but i'll have to implement myself a carousel. 
One last question: how can i set html elements inside Pano, like the toggle button that you did?
:)

**Comment by mudin** [comment]
@samirortiz You're welcome! I didn't set the button inside Pano, just use css and make `position: absolute`

**Comment by samirortiz** [comment]
thank you so much Mudin!!
