### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by jondavey** [mudin/vue-vr#8]
After installing using NPM I'm getting the following console error when attempting to compile. Any ideas what could be causing this? 

<img width="673" alt="Screen Shot 2019-07-23 at 5 03 06 PM" src="https://user-images.githubusercontent.com/823376/61747424-de0cd680-ad6b-11e9-8303-d8802f9ca788.png">

The formatted .min file places the error on this line.
<img width="948" alt="Screen Shot 2019-07-23 at 5 13 04 PM" src="https://user-images.githubusercontent.com/823376/61748024-3db7b180-ad6d-11e9-8ffb-b3fdcda74c6b.png">

Thanks!

**Comment by mudin** [comment]
@jondavey in what browser are you testing?

**Comment by jondavey** [comment]
Those errors were in Chrome. But checking in Safari I see different errors that seem to be coming from the Parcel bundler that I'm using as an alternative to webpack.
https://parceljs.org/
<img width="981" alt="Screen Shot 2019-07-25 at 9 57 35 AM" src="https://user-images.githubusercontent.com/823376/61881119-145d6980-aec4-11e9-90df-35f2046e1396.png">

**Comment by mudin** [comment]
@jondavey It could be the bundler issue. I cannot represent this issue using webpack

**Comment by jondavey** [comment]
Ok thanks. I'll look into things on that end.
